# Generated by Django 5.0.4 on 2024-05-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0002_usersmodel_reset_token_expiration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='reset_token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
