# Generated by Django 5.0.4 on 2024-05-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0004_subscriptionplan_subscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersmodel',
            name='subscription',
        ),
        migrations.RenameModel(
            old_name='SubscriptionPlan',
            new_name='Plans',
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_app.plans')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pdf_app.usersmodel')),
            ],
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pdf_app.payments'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
