# Generated by Django 5.0.4 on 2024-05-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0007_alter_payments_id_alter_plans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='ref_code',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
