# Generated by Django 5.0.4 on 2024-05-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0009_alter_payments_plan_alter_payments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='plan',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
