# Generated by Django 5.0.4 on 2024-05-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0010_alter_payments_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='paymentSource',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
