# Generated by Django 5.0.4 on 2024-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0011_payments_paymentsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='conversion_limit',
            field=models.IntegerField(default=0),
        ),
    ]
