# Generated by Django 5.0.4 on 2024-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0012_plans_conversion_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='conversion_count',
            field=models.IntegerField(default=0),
        ),
    ]
