# Generated by Django 5.0.4 on 2024-05-16 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0013_usersmodel_conversion_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='role',
            field=models.CharField(default='user', max_length=100),
        ),
        migrations.AddField(
            model_name='usersmodel',
            name='total_files',
            field=models.IntegerField(default=0),
        ),
    ]
