# Generated by Django 5.0.4 on 2024-05-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0017_alter_plans_conversion_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='conversion_limit',
            field=models.IntegerField(default=0),
        ),
    ]
