# Generated by Django 5.0.4 on 2024-05-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0019_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='conversion_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
