# Generated by Django 5.0.4 on 2024-05-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0020_alter_plans_conversion_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apikey',
            old_name='created',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='apikey',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
