# Generated by Django 5.0.4 on 2024-05-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0024_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
